config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: :index

  resources :blocks_supply
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root to: "home#index"
  delete 'users/sign_out'
  # get "blocks_supply#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/block_supply.rb
class BlockSupply < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blocks_supply, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :name, presence: true
  validates :phone_number, presence: true
  enum role: [:user, :dept_head, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery

  check_authorization unless: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number])
  end
end

app/controllers/blocks_supply_controller.rb
class BlocksSupplyController < ApplicationController
  skip_authorization_check
  def index
    @admin_blocks_supply = BlockSupply.all
  end

  def create
    # current_user
    @block_supply = BlockSupply.build(blocks_supply_params)
    # only admin can enter blocks supply data
    if @block_supply.save
      flash[:success] = "Your post has been created!"
      redirect_to blocks_supply_index_path
    else
      flash[:alert] = "Your new block supply data couldn't be created!  Please check the form."
      render 'new'
    end
  end

  def new
    @block_supply = BlockSupply.new
  end

  def destroy
    @blocks_supply = BlockSupply.find(params[:id])
    @blocks_supply.destroy
    redirect_to blocks_supply_path
  end

  private

  def blocks_supply_params
    params.require(:block_supply).permit(:name, :type_of_blocks, :number_of_blocks, :contact, :payment, :balance )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check
  def index
    render
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_authorization_check
  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/blocks_supply/_blocks_supply.html.erb
<% @admin_blocks_supply.each do |admin_blocks_supply| %>
    <small>Admin: <%= admin_blocks_supply.email %></small><br>
<% end %>

app/views/blocks_supply/create.html.erb
<section class='blocks-supply-data-entry'>
    <h2>Only Department Heads or Administrator can have access to this resource</h2>
    <%= form_with do |f| %>
        <div class="field">
            <%= f.label :name %><br />
            <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'supply-name-input' %>
        </div>
        <div class="field">
            <%= f.label :type %><br />
            <%= f.text_field :type, autofocus: true, autocomplete: "type", class: 'supply-type-input' %>
        </div>
        <div class="field">
            <%= f.label :number_of_blocks %><br />
            <%= f.text_field :number_of_blocks, autofocus: true, autocomplete: "number_of_blocks", class: 'supply-number-of-blocks-input' %>
        </div>
        <div class="field">
            <%= f.label :contact %><br />
            <%= f.text_field :contact, autofocus: true, autocomplete: "contact", class: 'supply-contact-input' %>
        </div>
        <div class="field">
            <%= f.label :payment %><br />
            <%= f.text_field :payment, autofocus: true, autocomplete: "payment", class: 'supply-payment-input' %>
        </div>
        <div class="field">
            <%= f.label :balance %><br />
            <%= f.text_field :balance, autofocus: true, autocomplete: "balance", class: 'supply-balance-input' %>
        </div>
        <div class="actions">
            <%= f.submit "Add Supply Data", class: 'blocks-supply-data-entry-btn' %>
        </div>
    <% end %>
</section>

app/views/blocks_supply/index.html.erb
<section class='All-supply-entry-information'>
    <h2>Here we will have a table of supply information</h2>
    <table>
        <thead>
            <tr>
                <th>Name of Customer</th>
                <th>Type of Block</th>
                <th>Number of Block</th>
                <th>Contact of Customer</th>
                <th>Payment made by Customer</th>
                <th>Balance of Payment</th>
            </tr>
        </thead>
        <tbody>
            <% @admin_blocks_supply.each do |block_supply| %>
                <tr>
                    <td><%= block_supply.name %></td>
                    <td><%= block_supply.type_of_blocks %></td>
                    <td><%= block_supply.number_of_blocks %></td>
                    <td><%= block_supply.contact %></td>
                    <td><%= block_supply.payment %></td>
                    <td><%= block_supply.balance %></td>
                </tr>
            <% end %>
        <tbody>
    </table>
</section>

app/views/blocks_supply/new.html.erb
<section class='blocks-supply-data-entry'>
    <h2>Only Department Heads or Administrator can have access to this resource</h2>
    <%= form_with(model: @block_supply, url: '/blocks_supply') do |f| %>
        <div class="field">
            <%= f.label :name %><br />
            <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'supply-name-input' %>
        </div>
        <div class="field">
            <%= f.label :type %><br />
            <%= f.text_field :type, autofocus: true, autocomplete: "type", class: 'supply-type-input' %>
        </div>
        <div class="field">
            <%= f.label :number_of_blocks %><br />
            <%= f.text_field :number_of_blocks, autofocus: true, autocomplete: "number_of_blocks", class: 'supply-number-of-blocks-input' %>
        </div>
        <div class="field">
            <%= f.label :contact %><br />
            <%= f.text_field :contact, autofocus: true, autocomplete: "contact", class: 'supply-contact-input' %>
        </div>
        <div class="field">
            <%= f.label :payment %><br />
            <%= f.text_field :payment, autofocus: true, autocomplete: "payment", class: 'supply-payment-input' %>
        </div>
        <div class="field">
            <%= f.label :balance %><br />
            <%= f.text_field :balance, autofocus: true, autocomplete: "balance", class: 'supply-balance-input' %>
        </div>
        <div class="actions">
            <%= f.submit "Add Supply Data", class: 'blocks-supply-data-entry-btn' %>
        </div>
    <% end %>
</section>

app/views/home/index.html.erb
<div>
    <h1 class="header">Welcome to MK Surveying and Construction</h1>
    <div class="row container-content">
        <div class="col s12 l4 xl4 left-side">
            <h2 class="office">We Undertake:</h2>
            <ul class="list">
                <li>Cadastral Survey</li>
                <li>Topographic Survey</li>
                <li>Land Demarcation</li>
                <li>Engineering Survey</li>
                <li>Setting Out</li>
                <li>Land Documentation</li>
                <li>Sales of land</li>
                <li>Building Construction</li>
            </ul>     
        </div>

        <div class="col s12 l4 xl4 middle">
            <h2 class="sale-of-blocks">Sale of Blocks</h2>
            <ul class="block-list flow-text">
                We have 5 inches and 6 inches solid and hollow blocks. Here is how we can make an order:
                <li>1. Register and Login</li>
                <li>2. Enter the type of block in the form provided: for example: 6 inches solid</li>
                <li>3. Enter the number of blocks: for example: 2000 blocks</li>
                <li>4. Enter the location to be delivered: for example: Tutu Akuapem</li>
                <li>5. Make your payments either through Bank or MoMo accounts</li>
                <li>6. Wait patiently for your order</li>
            </ul>
            <div>
                <% if current_user %>
                    <% if current_user.role === 'admin' || current_user.role === 'dept_head' %>
                        <%= link_to 'Add Blocks Supply Data', new_blocks_supply_path, class: 'light-blue lighten-2' %>
                    <% end %>
                <% end %>
            </div>
        </div>

        <div class="col s12 l4 xl4 right-side">
            <h2 class="tipper">Tipper Truck Services</h2>
            <p> For all your sand, stones, and gravels.
                Kindly contact the manager on 0504699947, then provide all required details for 
                a successful delivery and service
            </p>
        <div>
    </div>
</div>

app/views/layouts/_default.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="apple-mobile-web-app-capable" content="yes">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<link rel="manifest" href="/manifest.json">
<link rel="icon" href="/icon.png" type="image/png">
<link rel="icon" href="/icon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/icon.png">
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

app/views/layouts/_flash_msg.html.erb
<% flash.each do |msg_type, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{msg_type}")%>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
    <div class="container">
        © 2014 MK Surveying and Construction
    </div>
</footer>
            

app/views/layouts/_header.html.erb
<div class="navbar-fixed">
  <nav>
      <div class="nav-wrapper">
        <%= link_to "Mksurveying&construction", root_path, class: 'center' %>
        <ul class="left hide-on-med-and-down">
          <% if current_user %>
            <p>Hello <%= current_user.role %>!</p>
            <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'Signout-btn' %>
          <% else %>
            <li><%= link_to 'Log in', user_session_path, class: 'light-blue lighten-2' %>Login</li>
            <li><%= link_to 'Sign up', new_user_registration_path, class: 'yellow lighten-2' %>Register</a></li>
          <% end %>
          <li>ABOUT US</li>
          <li>OUR PROJECTS</li>
          <li>OUR SERVICES</li>
          <li>CONTACT US</li>
        </ul>
      </div>
  </nav>
</div>  

app/views/layouts/_materialize.html.erb
<%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons"' %>
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
<%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" %>
<%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Mksurveyconstruction" %></title>
    <%= render 'layouts/default'%>
    <%= render 'layouts/materialize'%>
    <%= yield :head %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <main class="container">
      <%= render 'layouts/flash_msg'%>
      <%= yield %>
    </main>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/users/_form.html.erb
<%= collection_select(
  :user, :role_id, Role.all, :id, :name, { prompt: true }
) %>

<div class="field">
  <%= form.label :email %><br>
  <%= form.text_field :email %>
</div>
<div class="field">
  <%= form.label :password %><br>
  <%= form.password_field :password, placeholder: "Leave blank if unchanged" %>
</div>

app/views/users/index.html.erb
<table>
    <caption>
        Users stored in the company database
    </caption>  
    <thead>
        <tr>
            <th scope="col">Customer Name</th>
            <th scope="col">Customer Email</th>
            <th scope="col">Phone Number</th>
            <th scope="col">Date Created</th>
            <th scope="col">Date Updated</th>
        <tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= user.phone_number %></td>
                <td><%= user.created_at %></td>
                <td><%= user.updated_at %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/show.html.erb
<%= user.role.name %>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>